config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  get 'pages/dashboard'
  get 'pages/ranking'

  resources :contact_activities, :except => :index
  resources :activities
  resources :contacts
  resources :campaigns
  resources :campaign_types

  root 'pages#dashboard'

end

app/models/contact_activity.rb
class ContactActivity < ActiveRecord::Base
  belongs_to :contact, counter_cache: true
  belongs_to :campaign
  belongs_to :activity
end

app/controllers/contact_activities_controller.rb
class ContactActivitiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_contact_activity, only: [:show, :edit, :update, :destroy]

  # GET /contact_activities/1
  # GET /contact_activities/1.json
  def show
  end

  # GET /contact_activities/new
  def new
    @contact_activity = ContactActivity.new
  end

  # GET /contact_activities/1/edit
  def edit
  end

  # POST /contact_activities
  # POST /contact_activities.json
  def create
    @contact_activity = ContactActivity.new(contact_activity_params)

    respond_to do |format|
      if @contact_activity.save
        format.html { redirect_to @contact_activity, notice: 'Contact activity was successfully created.' }
        format.json { render :show, status: :created, location: @contact_activity }
      else
        format.html { render :new }
        format.json { render json: @contact_activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contact_activities/1
  # PATCH/PUT /contact_activities/1.json
  def update
    respond_to do |format|
      if @contact_activity.update(contact_activity_params)
        format.html { redirect_to @contact_activity, notice: 'Contact activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact_activity }
      else
        format.html { render :edit }
        format.json { render json: @contact_activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contact_activities/1
  # DELETE /contact_activities/1.json
  def destroy
    @contact_activity.destroy
    respond_to do |format|
      format.html { redirect_to contact_activities_url, notice: 'Contact activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact_activity
      #@contact_activity = ContactActivity.find(params[:id])
      @contact = Contact.find(params[:id])
      @contact_activities = ContactActivity.where(contact_id: params[:id]).order(created_at: :desc)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_activity_params
      params.require(:contact_activity).permit(:contact_id, :campaign_id, :activity_id, :description)
    end
end

app/helpers/contact_activities_helper.rb
module ContactActivitiesHelper
end

app/views/contact_activities/_form.html.erb
<%= simple_form_for(@contact_activity) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :contact %>
    <%= f.association :campaign %>
    <%= f.association :activity %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/contact_activities/edit.html.erb
<h1>Editing Contact Activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact_activity %> |
<%= link_to 'Back', contact_activities_path %>

app/views/contact_activities/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            <i class="fa fa-fw fa-area-chart color-3"></i> Actividades recientes: <small>contactos</small>
        </h1>
        <ol class="breadcrumb">
            <%= nav_link "Escritorio", pages_dashboard_path, 'fa fa-tachometer' %>
            <%= nav_link "Listado", contacts_path, 'fa fa-table' %>
        </ol>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="table-responsive">
            <table id="tablacredo" class="display table table-bordered table-hover">
                <thead>
                    <tr>
                        <th>Contacto</th>
                        <th>Campaña</th>
                        <th>Última actividad</th>
                        <th>Descripción</th>
                        <th class="text-center">Ver</th>
                        <th class="text-center">Editar</th>
                        <th class="text-center">Eliminar</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Contacto</th>
                        <th>Campaña</th>
                        <th>Última actividad</th>
                        <th>Descripción</th>
                        <th class="text-center">Ver</th>
                        <th class="text-center">Editar</th>
                        <th class="text-center">Eliminar</th>
                    </tr>
                </tfoot>
                <tbody>
                  <% @contact_activities.each do |contact_activity| %>
                    <tr>
                      <td><%= contact_activity.contact %></td>
                      <td><%= contact_activity.campaign %></td>
                      <td><%= contact_activity.activity %></td>
                      <td><%= contact_activity.description %></td>

                      <td width="7%" align="center">
                        <%= link_to contact_activity do %>
                          <i class="fa fa-eye"></i>
                        <% end %>
                      </td>
                      <td width="7%" align="center">
                        <%= link_to edit_contact_activity_path(contact_activity) do %>
                          <i class="fa fa-fw fa-pencil"></i>
                        <% end %>
                      </td>
                      <td width="7%" align="center">
                        <%= link_to contact_activity, method: :delete, data: { confirm: 'Are you sure?' } do %>
                        <i class="fa fa-trash"></i>
                        <% end %>
                      </td>

                    </tr>
                  <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>


<br>

<%= link_to 'New Contact activity', new_contact_activity_path %>

app/views/contact_activities/new.html.erb
<h1>New Contact Activity</h1>

<%= render 'form' %>

<%= link_to 'Back', contact_activities_path %>

app/views/contact_activities/show.html.erb
<style>
  body {
    background-color: #E6E6E6;
  }
</style>

<div class="row top20">
    <div class="col-lg-12">
        <h1 class="page-header">
            <i class="fa fa-fw fa-calendar-check-o color-3"></i> Actividades de <%= @contact.first_name.blank? ? @contact.email : @contact.first_name %>
        </h1>
        <ol class="breadcrumb">
            <%= nav_link "Escritorio", pages_dashboard_path, 'fa fa-tachometer' %>
            <%= nav_link "Listado", contacts_path, 'fa fa-table' %>


            <li class="active">
                <i class="fa fa-user"></i> Actividades de <%= @contact.first_name %>
            </li>
        </ol>
    </div>
</div>

<div class="row">
   <div class="col-md-8 col-sm-12 top20" >
       <div >
           <ul class="timeline">
              <li class="time-label">
                <span class="color-3-bg"> <%= @contact_activities.count %> Actividades</span>
              </li>
              <% @contact_activities.each do |contact_activity| %>
              <li>
                <i class="fa fa-bullhorn bg-camp"></i>
                <div class="timeline-item">
                  <span class="time">
                    <i class="fa fa-calendar"></i>
                    <%= contact_activity.created_at.strftime('%d/%m/%Y %H:%M hrs.') %>
                  </span>
                  <h3 class="timeline-header"><%= contact_activity.activity.description %> en campaña: <%= link_to contact_activity.campaign.name, campaign_path(contact_activity.campaign) %></h3>
                  <div class="timeline-body">
                    <%= contact_activity.description.html_safe %>
                  </div>
                </div>
              </li>
              <% end %>
               <li>
                  <i class="fa fa-clock-o"></i>
               </li>
           </ul>
       </div>
   </div>
</div>

<p id="notice"><%= notice %></p>

<br />

<%= link_to 'Volver', contact_activities_path %>