config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  get 'pages/dashboard'
  get 'pages/ranking'

  resources :contact_activities, :except => :index
  resources :activities
  resources :contacts
  resources :campaigns
  resources :campaign_types

  root 'pages#dashboard'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  has_many :contact_observations, dependent: :destroy
  has_many :contact_activities, dependent: :destroy
  has_one :contact_information, dependent: :destroy
  accepts_nested_attributes_for :contact_observations, reject_if: proc { |attributes| attributes['comment'].blank? }
  accepts_nested_attributes_for :contact_information

  scope :group_by_month,   -> { group("date_trunc('month', created_at) ") }


  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |contact|
        csv << contact.attributes.values_at(*column_names)
      end
    end
  end

  scope :this_month, -> { where(created_at: Time.now.beginning_of_month..Time.now.end_of_month) }

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_contact, only: [:show, :show_activities, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
    respond_to do |format|
      format.html
      format.json { render json: ContactDatatable.new(view_context) }
      format.csv { send_data @contacts.to_csv }
      format.xls # { send_data @products.to_csv(col_sep: "\t")
    end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @campaign = Campaign.find_by name: @contact.source

  end

  # GET /contacts/new
  def new
    @contact = Contact.new
    @contact.contact_observations.build
    @contact.build_contact_information
  end

  # GET /contacts/1/edit
  def edit
    @contact.contact_observations.build
    
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :email, :source, :donor, contact_information_attributes: [:rut, :birthdate, :phone, :address, :commune, :region], contact_observations_attributes: [:comment, :id])
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= simple_form_for(@contact) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :first_name , :label => "Nombre"%>
    <%= f.input :last_name , :label => "Apellidos"%>
    <%= f.input :email, :label => "Correo Electrónico" %>

    <%= f.simple_fields_for :contact_information do |builder| %>
      <%= builder.input :rut, :label => "RUT" %>
      <%= builder.input :birthdate, as: :date, start_year: Date.today.year - 90,
                             end_year: Date.today.year - 12, discard_day: false,
                             order: [:day, :month, :year] %>
      <%= builder.input :phone, :label => "Teléfono" %>
      <%= builder.input :address, :label => "Direccion" %>
      <%= builder.input :commune, :label => "Comuna" %>
      <%= builder.input :region, :label => "Región" %>


    <% end %>

    <label>Fuente</label><br>
    <%= f.collection_select(:source, Campaign.all, :name, :name, {:selected => "Registro Manual"}) %>
    <br><br>
    <%= f.label :donor, :label => "Tipo de Donante" %>
    <%= f.select(:donor, options_for_select(['Mensual', 'Único', 'Valor', 'Modalidad'], 3),
                        {})

                         %>
  </div>

  <%= f.simple_fields_for :contact_observations do |builder| %>
    <%= builder.input :comment, :label => "Comentarios" %>
  <% end %>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<div class="row">
    <div class="col-lg-12">

        <h1 class="page-header">
          <i class="fa fa-pencil-square-o color-1"></i> Editar contacto: <small><%= @contact.first_name %></small>
        </h1>

        <ol class="breadcrumb">
            <%= nav_link "Escritorio", pages_dashboard_path, 'fa fa-tachometer' %>
            <%= nav_link "Listado", contacts_path, 'fa fa-table' %>
            <li class="active">
                <i class="fa fa-user"></i> Editar contacto <%= @contact.first_name %>
            </li>
        </ol>
    </div>
</div>

<div class="row">
    <div class="col-lg-8">
       <%= render 'form' %>
    </div>
</div>

<br />

<%= link_to 'Ver', @contact %> |
<%= link_to 'Volver', contacts_path %>

app/views/contacts/index.html.erb
  <p id="notice"><%= notice %></p>

  <!-- Page Heading -->
  <div class="row">
      <div class="col-lg-12">
          <h1 class="page-header">
              <i class="fa fa-fw fa-users color-1"></i> Lista de Contactos
          </h1>
          <ol class="breadcrumb">
              <%= nav_link "Escritorio", pages_dashboard_path, 'fa fa-tachometer' %>
              <%= nav_link "Listado", contacts_path, 'fa fa-table' %>
          </ol>
      </div>
  </div>

  <div class="row">
      <div class="col-lg-12">
          <h2>Datos de contactos <small>Descargar: <%= link_to 'CSV', contacts_path(format: 'csv') %> | <%= link_to 'Excel', contacts_path(format: 'xls') %></small></h2>
          <div class="table-responsive">
              <table id="list_contacts" class="table table-striped table-bordered" data-source="<%= contacts_url(format: 'json') %>">
                  <thead>
                      <tr>
                          <th>ID</th>
                          <th>Nombre</th>
                          <th>Apellido</th>
                          <th>Correo</th>
                          <th>Activo en</th>
                          <th>Última actividad</th>
                          <th class="text-center">Ver más</th>
                          <th class="text-center">Actividades</th>
                          <th class="text-center">Acciones</th>

                      </tr>
                  </thead>
                  <tbody>
                  </tbody>
              </table>
          </div>
      </div>
  </div>

  <br>

  <%= link_to 'Agregar nuevo contacto', new_contact_path, class: "btn-credo" %>

  <% content_for :js_footer do %>
    <%= javascript_include_tag 'contacts' %>
  <% end %>

app/views/contacts/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Nombre</Data></Cell>
        <Cell><Data ss:Type="String">Apellidos</Data></Cell>
        <Cell><Data ss:Type="String">Email</Data></Cell>
        <Cell><Data ss:Type="String">Fuente</Data></Cell>
        <Cell><Data ss:Type="String">Actividades</Data></Cell>
      </Row>
    <% @contacts.each do |contact| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= contact.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= contact.first_name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= contact.last_name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= contact.email %></Data></Cell>
        <Cell><Data ss:Type="String"><%= contact.source %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= contact.activities_count %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/contacts/new.html.erb
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            <i class="fa fa-user-plus color-1"></i> Agregar nuevo contacto
        </h1>
        <ol class="breadcrumb">
            <%= nav_link "Escritorio", pages_dashboard_path, 'fa fa-tachometer' %>
            <%= nav_link "Listado", contacts_path, 'fa fa-table' %>
            <li class="active">
                <i class="fa fa-user-plus"></i> Agregar nuevo contacto
            </li>
        </ol>
    </div>
</div>
<br>
<div class="row">
    <div class="col-lg-8">
        <%= render 'form' %>
    </div>
</div>
<br>
<%= link_to 'Volver', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>


<div class="row">
    <div class="col-lg-12">

        <h1 class="page-header">
          Perfil de <%= @contact.first_name.blank? ? @contact.email : @contact.first_name %>
        </h1>

        <ol class="breadcrumb">
            <%= nav_link "Escritorio", pages_dashboard_path, 'fa fa-tachometer' %>
            <%= nav_link "Listado", contacts_path, 'fa fa-table' %>
            <li class="active">
                <i class="fa fa-user"></i> Perfil de <%= @contact.first_name %>
            </li>
        </ol>
    </div>
</div>

<div class="row">
  <div class="col-md-6">
    <table class="table table-user-information">
      <tbody>
        <tr>
          <td><strong>Nombre:</strong></td>
          <td><%= @contact.first_name %></td>
        </tr>
        <tr>
          <td><strong>Apellido:</strong></td>
          <td><%= @contact.last_name %></td>
        </tr>
        <tr>
          <td><strong>Email:</strong></td>
          <td><%= @contact.email %></td>
        </tr>
        <tr>
          <td><strong>Source:</strong></td>
          <td><%= unless @contact.source.blank?
                    link_to @contact.source, campaign_path(@campaign)

                else  "No hay fuente definida"
                end%></td>
        </tr>
        <tr>
          <td><strong>Fecha Nacimiento:</strong></td>
          <td><%= @contact.contact_information.birthdate unless @contact.contact_information.nil? %></td>
        </tr>
        <tr>
          <td><strong>Teléfono:</strong></td>
          <td><%= @contact.contact_information.phone unless @contact.contact_information.nil? %></td>
        </tr>
        <tr>
          <td><strong>Direccion:</strong></td>
          <td><%= @contact.contact_information.address unless @contact.contact_information.nil? %></td>
        </tr>
        <tr>
          <td><strong>Comuna:</strong></td>
          <td><%= @contact.contact_information.commune unless @contact.contact_information.nil? %></td>
        </tr>
        <tr>
          <td><strong>Region:</strong></td>
          <td><%= @contact.contact_information.region unless @contact.contact_information.nil? %></td>
        </tr>
        <tr>
          <td><strong>Número de Participaciones</strong></td>
          <td><%= @contact.activities_count %></td>
        </tr>
        <tr>
          <td><strong>Tipo de Donante</strong></td>
          <td><%= @contact.donor %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>



<% if @contact.contact_observations.present? %>
<div class="row">
  <div class="col-md-6">
  <strong>Observaciones</strong>
  <% @contact.contact_observations.each do |o| %>
    <div class="caja-observaciones">
      <span class="fecha-o"><%= o.updated_at.strftime("%B %e, %Y") %></span>
      <%= o.comment %>
    </div>
  <% end %>
  </div>
</div>
<% end %>


<%= link_to 'Editar', edit_contact_path(@contact) %> |
<%= link_to 'Ver Actividades', contact_activity_path(@contact) %> |
<%= link_to 'Volver', contacts_path %>

app/views/contacts/show_activities.html.erb
<h1>Actividad de: <%= @contact.first_name %></h1>
<ul>
  <% @activities.each do |activity| %>
    <li><%= activity.description.html_safe %></li>
  <% end %>
</ul>