config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  get 'pages/dashboard'
  get 'pages/ranking'

  resources :contact_activities, :except => :index
  resources :activities
  resources :contacts
  resources :campaigns
  resources :campaign_types

  root 'pages#dashboard'

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  belongs_to :campaign_type
  has_many :contact_activities
end

app/models/campaign_type.rb
class CampaignType < ActiveRecord::Base
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_campaign, only: [:show, :edit, :update, :destroy]

  # GET /campaigns
  # GET /campaigns.json
  def index
    # @campaigns = Campaign.all
    respond_to do |format|
      format.html
      format.json { render json: CampaignDatatable.new(view_context) }
    end
  end

  # GET /campaigns/1
  # GET /campaigns/1.json
  def show
  end

  # GET /campaigns/new
  def new
    @campaign = Campaign.new
  end

  # GET /campaigns/1/edit
  def edit
  end

  # POST /campaigns
  # POST /campaigns.json
  def create
    @campaign = Campaign.new(campaign_params)

    respond_to do |format|
      if @campaign.save
        format.html { redirect_to @campaign, notice: 'Campaign was successfully created.' }
        format.json { render :show, status: :created, location: @campaign }
      else
        format.html { render :new }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campaigns/1
  # PATCH/PUT /campaigns/1.json
  def update
    respond_to do |format|
      if @campaign.update(campaign_params)
        format.html { redirect_to @campaign, notice: 'Campaign was successfully updated.' }
        format.json { render :show, status: :ok, location: @campaign }
      else
        format.html { render :edit }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaigns/1
  # DELETE /campaigns/1.json
  def destroy
    @campaign.destroy
    respond_to do |format|
      format.html { redirect_to campaigns_url, notice: 'Campaign was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campaign
      @campaign = Campaign.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def campaign_params
      params.require(:campaign).permit(:name, :campaign_type_id)
    end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/_form.html.erb
<%= simple_form_for(@campaign) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.association :campaign_type, label_method: :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/campaigns/edit.html.erb
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            <i class="fa fa-pencil-square-o color-2"></i> Editar Campaña: <small><%= @campaign.name %></small>
        </h1>
        <ol class="breadcrumb">
            <%= nav_link "Escritorio", pages_dashboard_path, 'fa fa-tachometer' %>
            <%= nav_link "Listado", campaigns_path, 'fa fa-table' %>
            <li class="active">
                <i class="fa fa-pencil-square-o"></i> Editar Campaña
            </li>
        </ol>
    </div>
</div>
<div class="row">
    <div class="col-lg-8">
        <%= render 'form' %>
    </div>
</div>

<br />

<%= link_to 'Ver', @campaign %> |
<%= link_to 'Volver', campaigns_path %>

app/views/campaigns/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            <i class="fa fa-fw fa-bullhorn color-2"></i> Listado de Campañas
        </h1>
        <ol class="breadcrumb">
            <%= nav_link "Escritorio", pages_dashboard_path, 'fa fa-tachometer' %>
            <%= nav_link "Listado campañas", campaigns_path, 'fa fa-table' %>
        </ol>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <h2>Datos de campañas</h2>
        <div class="table-responsive">
            <table id="list_campaigns" class="display table table-bordered table-hover" data-source="<%= campaigns_url(format: 'json') %>">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Tipo de campaña</th>
                        <th>Fecha de creación</th>
                        <th class="text-center"></th>
                        <th class="text-center"></th>
                        <th class="text-center"></th>
                    </tr>
                </thead>
                <!-- <tfoot>
                    <tr>
                        <th>Nombre</th>
                        <th>Tipo de campaña</th>
                        <th class="text-center">Ver</th>
                        <th class="text-center">Editar</th>
                        <th class="text-center">Eliminar</th>
                    </tr>
                </tfoot> -->
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
</div>

<br>

<%= link_to 'Agregar nueva Campaña', new_campaign_path, class: "btn-credo" %>

<% content_for :js_footer do %>
  <%= javascript_include_tag 'campaigns' %>
<% end %>

app/views/campaigns/new.html.erb
<div class="row">
    <div class="col-lg-8">
        <h1 class="page-header">
            <%= image_tag("campagnadd.svg", :alt => "icono", :width => "43", :class => "verticalbot") %> Agregar nueva campaña
        </h1>
        <ol class="breadcrumb">
            <%= nav_link "Escritorio", pages_dashboard_path, 'fa fa-tachometer' %>
            <%= nav_link "Listado", campaigns_path, 'fa fa-table' %>
            <li class="active">
                <%= image_tag("campagnadd.svg", :alt => "icono", :width => "18", :class => "verticalbot") %> Agregar nueva campaña
            </li>
        </ol>
    </div>
</div>

<div class="row">
    <div class="col-lg-8">
        <%= render 'form' %>
    </div>
</div>

<br />

<%= link_to 'Volver', campaigns_path %>

app/views/campaigns/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            Detalle Campaña: <small><%= @campaign.name %></small>
        </h1>
        <ol class="breadcrumb">
            <%= nav_link "Escritorio", pages_dashboard_path, 'fa fa-tachometer' %>
            <%= nav_link "Listado", campaigns_path, 'fa fa-table' %>
            <li class="active">
                Editar Campaña
            </li>
        </ol>
    </div>
</div>

<div class="row">
  <div class="col-md-6">
    <table class="table table-user-information">
      <tbody>
        <tr>
          <td><strong>Nombre de Campaña:</strong></td>
          <td><%= @campaign.name %></td>
        </tr>
        <tr>
          <td><strong>Tipo de campaña:</strong></td>
          <td><%= @campaign.campaign_type.description %></td>
        </tr>
        <tr>
          <td><strong>Creación:</strong></td>
          <td><%= @campaign.created_at.strftime('%d/%m/%Y %H:%M hrs.') %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <%= link_to 'Editar', edit_campaign_path(@campaign) %> |
    <%= link_to 'Volver', campaigns_path %>
  </div>
</div>


<div class="row">
  <div class="col-md-12">
  <h3>Contactos que participaron (<%= @campaign.contact_activities.count %>)</h3>
    <table class="table table-user-information">
      <tbody>
        <% @campaign.contact_activities.each.with_index(1) do |activity, index| %>
        <tr>
          <td><%= index %></td>
          <td><%= link_to activity.contact.email, contact_path(activity.contact) %></td>
          <td><%= activity.created_at.strftime('%d/%m/%Y %H:%M hrs.') %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>