config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  get 'pages/dashboard'
  get 'pages/ranking'

  resources :contact_activities, :except => :index
  resources :activities
  resources :contacts
  resources :campaigns
  resources :campaign_types

  root 'pages#dashboard'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Credosys</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    params[:controller], media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= yield :js_head %>
  <script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js" charset="utf-8"></script>
  <script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js" charset="utf-8"></script>
  <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.flash.min.js" charset="utf-8"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js" charset="utf-8"></script>
  <script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js" charset="utf-8"></script>
  <script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js" charset="utf-8"></script>
  <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js" charset="utf-8"></script>
  <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.print.min.js" charset="utf-8"></script>
</head>
<body class="<%= params[:controller] %>_controller">
  <div id="wrapper">

  <!-- Navigation -->
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
          </button>
          <%= link_to root_path, class: 'navbar-brand' do  %>
            <%= image_tag("logo-admin.png", :alt => "Logocredo", :width => "120") %>
          <% end %>
      </div>
      <!-- Top Menu Items -->
      <ul class="nav navbar-right top-nav">
          <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> <%= current_user.email %> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                  <li>
                      <%= link_to edit_user_registration_path do  %>
                        <i class="fa fa-fw fa-user"></i> Perfil
                      <% end %>
                  </li>
                  <!-- <li>
                      <a href="#"><i class="fa fa-fw fa-gear"></i> Opciones</a>
                  </li> -->
                  <li class="divider"></li>
                  <li>
                      <%= link_to destroy_user_session_path, :method => :delete do %>
                        <i class="fa fa-fw fa-power-off"></i> Salir
                      <% end %>
                  </li>
              </ul>
          </li>
      </ul>
      <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav side-nav">

              <%= nav_link " Escritorio", pages_dashboard_path, 'fa fa-fw fa-tachometer' %>

              <li class="menu-contact">
                  <a href="javascript:;" data-toggle="collapse" data-target="#demo"><i class="fa fa-fw fa-users"></i> Contactos <i class="fa fa-fw fa-caret-down"></i>
                  </a>
                  <ul id="demo" class="">
                      <%= nav_link "Listado", contacts_path %>
                      <%= nav_link "Agregar nuevo", new_contact_path %>
                  </ul>
              </li>
              <li class="menu-campaigns">
                  <a href="javascript:;" data-toggle="collapse" data-target="#demo2"><i class="fa fa-fw fa-bullhorn"></i> Campañas <i class="fa fa-fw fa-caret-down"></i></a>
                  <ul id="demo2" class="collapse">
                      <%= nav_link "Listado", campaigns_path %>
                      <%= nav_link "Agregar nueva", new_campaign_path %>
                      <%= nav_link "Tipos de campaña", campaign_types_path %>
                  </ul>
              </li>
              <li class="menu-activities">
                  <a href="javascript:;" data-toggle="collapse" data-target="#demo3"><i class="fa fa-fw fa-area-chart"></i> Actividad <i class="fa fa-fw fa-caret-down"></i></a>
                  <ul id="demo3" class="collapse">
                      <%# nav_link "Contactos", contact_activities_path %>
                      <%# nav_link "Agregar nueva", new_contact_activity_path %>
                      <%= nav_link "Tipos de actividad", activities_path %>
                  </ul>
              </li>
          </ul>
      </div>
      <!-- /.navbar-collapse -->
  </nav>

  <div id="page-wrapper">

    <div class="container-fluid">

      <%= yield %>

    </div>

  </div>

  </div>
<%= yield :js_footer %>
<%= yield :charts_js %>
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Credosys</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag   'devise', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= params[:controller] %>_controller">
  <div id="wrapper">

  <!-- Navigation -->
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
          </button>
          <%= link_to root_path, class: 'navbar-brand' do  %>
            <%= image_tag("logo-admin.png", :alt => "Logocredo", :width => "120") %>
          <% end %>
      </div>
      <!-- Top Menu Items -->
      <ul class="nav navbar-right top-nav">
          <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> Ingresar <b class="caret"></b></a>
          </li>
      </ul>
      <!-- /.navbar-collapse -->
  </nav>

  <div id="page-wrapper">

    <div class="container-fluid">

      <div class="container-fluid top50">
        <div class="col-md-4 col-md-offset-4 col-xs-12 login">

          <%= yield %>

        </div>
      </div>

    </div>

  </div>

  </div>


</body>
</html>